.\" Copyright (c) 2010, Stefano Rivera
.\" Released under terms of the MIT/X/Expat Licence. See COPYING for details.
.TH IBID-DB "1" "January 2010" "ibid-db 0.0" "User Commands"
.SH NAME
ibid-db \- Database management utilitiy for Ibid (chat bot)
.SH SYNOPSIS
.B ibid-db command
[\fIoptions\fR...]
.SH DESCRIPTION
This utility is for offline management of your Ibid bot's database.
Used for import, export, and upgrades.
.P
The export format is DBMS-agnostic and can be used to migrate between different
databases.
.SH COMMANDS
.TP
\fB\-e\fR FILE, \fB\-\-export\fR=\fIFILE\fR
Export DB contents to FILE.
Export format is JSON.
.IP
FILE can be \- for stdin/stdout or can end in .gz for automatic Gzip
compression.
.TP
\fB\-i\fR FILE, \fB\-\-import\fR=\fIFILE\fR
Import DB contents from FILE as exported by this utility.
.IP
FILE can be \- for stdin/stdout or can end in .gz for automatic Gzip
compression.
.IP
\fBNote: \fRThe DB must be empty first.
.TP
\fB\-u\fR, \fB\-\-upgrade\fR
Upgrade DB schema to the latest version.
You need to run this after upgrading your bot.
.IP
\fBNote: \fRYou should backup first.
.SH OPTIONS
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Turn on debugging output to STDERR.
.SH FILES
.TP
\fIibid.ini\fR
Locates the database to act upon by looking for the \fB[databases].ibid\fR value
in the bot configuration file in the current directory.
.SH SEE ALSO
ibid.ini(5),
ibid-setup(1),
.UR http://ibid.omnia.za.net/
.BR http://ibid.omnia.za.net/
