.\" Copyright (c) 2010, Stefano Rivera
.\" Released under terms of the MIT/X/Expat Licence. See COPYING for details.
.TH IBID-DB "1" "January 2010" "Ibid 0.0" "Multi-protocol Chat Bot"
.SH NAME
ibid-knab-import \- Knab->Ibid Import utility for Ibid (the multi-protocol chat
bot)
.SH SYNOPSIS
.B ibid-knab-import
.I knab-sa-url
.I source
.RI [ config-file ]
.SH DESCRIPTION
This utility imports users, seen, factoids, and URLs from a Knab bot's database
into an Ibid.
.P
For best results, import directly into a brand new, clean Ibid install.
.P
On import, strings are converted to unicode, guessing UTF-8 and falling back to
detection.
.SH OPTIONS
.TP
.I knab-sa-url
The SQLAlchemy URI for the Knab's database.
The format is
.BI mysql:// user : pass @ hostname / dbname
.TP
.I source
The name in the Ibid bot for the source that the knab was previously connected to.
.TP
.I config-file
If supplied, this is configuration file is used for locating the Ibid's
database rather than \fBibid.ini\fR.
.SH FILES
.TP
.I ibid.ini
Locates the database to act upon by looking for the \fB[databases].ibid\fR value
in the bot configuration file in the current directory.
.SH SEE ALSO
.BR ibid (1),
.BR ibid.ini (5),
.BR ibid-setup (1),
.UR http://ibid.omnia.za.net/
.BR http://ibid.omnia.za.net/
