.\" Copyright (c) 2010, Stefano Rivera
.\" Released under terms of the MIT/X/Expat Licence. See COPYING for details.
.TH IBID-SETUP "1" "January 2010" "Ibid 0.0" "Multi-protocol Chat Bot"
.SH NAME
ibid-setup \- Create a configuration file and Database for an Ibid multi-protocol chat bot
.SH SYNOPSIS
.B ibid-setup
.SH DESCRIPTION
This program installs a new Ibid bot.
It asks a series of questions about the new bot, and writes out a basic
configuration file - \fBibid.ini\fR (5) - to the current directory.
It also creates a database for the bot, by default a SQLite database in
the current directory.
.P
This should be run in the directory which will become the new Ibid bot's
base.
.P
Should there be an existing \fBibid.ini\fR in the current directory, it
will be used, and the only questions asked will be for adding an
administrative user. These can safely be skipped with a \fB^C\fR.
.SH FILES
.TP
.I ibid.ini
The Ibid bot's configuration file, will be created if it doesn't exist.
.SH SEE ALSO
.BR ibid (1),
.BR ibid.ini (5),
.UR http://ibid.omnia.za.net/
.BR http://ibid.omnia.za.net/
