.\" Copyright (c) 2010, Stefano Rivera
.\" Released under terms of the MIT/X/Expat Licence. See COPYING for details.
.TH IBID "1" "January 2010" "Ibid 0.0" "Multi-protocol Chat Bot"
.SH NAME
ibid \- Run Ibid (the multi-protocol chat bot)
.SH SYNOPSIS
.B ibid
.RI [ config-file ]
.SH DESCRIPTION
This runs an Ibid bot in the foreground.
.P
There should there be an existing \fBibid.ini\fR in the current
directory, or one should be provided on the command line.
.SH BUGS
Note that you should use
.BR twistd (1)
where possible instead of calling this directly, as certain classes of
error (problems in twisted callbacks) will go unnoticed in this program.
That has no harmful effects, but the developers may miss out on some
good bug reports.
.SH FILES
.TP
.I ibid.ini
The Ibid bot's configuration file, will be created if it doesn't exist.
.SH SEE ALSO
.BR ibid (1),
.BR ibid.ini (5),
.BR twistd (1),
.UR http://ibid.omnia.za.net/
.BR http://ibid.omnia.za.net/
