#!/usr/bin/env python
# Copyright (c) 2008-2009, Michael Gorven
# Released under terms of the MIT/X/Expat Licence. See COPYING for details.

from optparse import OptionParser

from twisted.internet import reactor
import ibid

parser = OptionParser(usage='%prog [options] <config filename>')
options, args = parser.parse_args(values={})

options['config'] = len(args) > 0 and args[0] or 'ibid.ini'

ibid.setup(options)
reactor.run()

# vi: set et sta sw=4 ts=4:
