#!/usr/bin/env python

from sys import argv, exit, stderr
from os.path import basename, exists
from optparse import OptionParser

from simplejson import loads

import ibid
from ibid.config import FileConfig
from ibid.plugins.factoid import Factoid, FactoidName, FactoidValue, Factpack

parser = OptionParser(usage=u'%prog <factpack>')
parser.add_option('-r', '--remove', action='store_true')
options, args = parser.parse_args()

if len(args) != 1:
    parser.error(u'No factpack specified')

filename = args[0]

ibid.options = {'base': '.'}
ibid.config = FileConfig("ibid.ini")
ibid.config.merge(FileConfig("local.ini"))
ibid.reload_reloader()
ibid.reloader.reload_databases()
session = ibid.databases.ibid()
session.begin()

if options.remove:
    factpack = session.query(Factpack).filter_by(name=filename).first()
    if not factpack:
        print >> stderr, u'Factpack not loaded'
        exit(3)

    for fname in session.query(FactoidName).filter_by(factpack=factpack.id).all():
        session.delete(fname)
    for fvalue in session.query(FactoidValue).filter_by(factpack=factpack.id).all():
        session.delete(fvalue)

    session.delete(factpack)
    session.commit()
    session.close()

    print u"Factpack removed"
    exit(0)

if not exists(filename):
    print >> stderr, u"File doesn't exist"
    exit(3)

try:
    facts = loads(open(filename).read())
except ValueError, e:
    print >> stderr, u"Invalid factpack"
    exit(4)

name = basename(filename).replace('.json', '')
factpack = session.query(Factpack).filter_by(name=name).first()
if factpack:
    print >> stderr, u'Factpack is already imported'
    exit(5)

factpack = Factpack(name)
session.save(factpack)
session.flush()

for names, values in facts:
    factoid = Factoid()
    for name in names:
        fname = FactoidName(unicode(name), None)
        fname.factpack = factpack.id
        factoid.names.append(fname)
    for value in values:
        fvalue = FactoidValue(unicode(value), None)
        fvalue.factpack = factpack.id
        factoid.values.append(fvalue)
    session.save(factoid)

session.commit()
session.close()
print "Factpack imported"

# vi: set et sta sw=4 ts=4:
