#!/usr/bin/env python

import optparse
import sys

import dateutil
import matplotlib.pyplot as pyplot
from matplotlib.dates import date2num
import numpy

parser = optparse.OptionParser(usage="""%prog logfile
logfile is a memory log file (possibly gzipped)""")
parser.add_option('-o', '--output', dest='output', metavar='FILE',
        help='Output to filename rather than interactive')
parser.add_option('-d', '--dpi', dest='dpi',
        help='Output DPI')
parser.add_option('-b', '--botname', dest='botname', default='Ibid', metavar='NAME',
        help='Bot Name (Graph Title)')

(options, args) = parser.parse_args()

if len(args) != 1:
    sys.stderr.write("Log file required\n")
    sys.exit(2)

data = numpy.loadtxt(args[0],
        dtype=float,
        delimiter=',',
        converters={0: lambda x: date2num(dateutil.parser.parse(x))},
        usecols=(0, 2, 3, 4))

fig = pyplot.figure()
ax_obj = fig.add_subplot(111)
ax_obj.set_xlabel('time (s)')
ax_mem = ax_obj.twinx()
ax_mem.grid(True)

ax_obj.plot_date(data[:,0], data[:,1]/1000, 'b-', label='Objects (k)')
ax_obj.set_ylabel('Objects (k)', color='b')

for tl in ax_obj.get_yticklabels():
    tl.set_color('b')

ax_mem.plot_date(data[:,0], data[:,2]/1024, 'r-', label='VM Size')
ax_mem.plot_date(data[:,0], data[:,3]/1024, 'g-', label='VM RSS')

ax_mem.set_ylabel('Memory (MiB)')

pyplot.legend(loc='best')
pyplot.title(options.botname + ' Memory Usage')

fig.autofmt_xdate()

if options.output:
    pyplot.savefig(options.output, dpi=options.dpi)
else:
    pyplot.show()

# vi: set et sta sw=4 ts=4:
